### ISSUE TITLE
Snake game in C language for Linux( or Linux and Windows both) required. Windows one is done.

### ISSUE THREAD

**Issue by skohan** [sohan-k/Snake-game#6]
Snake game implementation in C language is required. Just make a new folder named 'C' and create PR.

**Comment by amanhasnonamee** [comment]
I already have this.

**Comment by skohan** [comment]
Cool! You can create a folder named C and put your code there and leave a PR.

**Comment by codewdhruv** [comment]
i have the linux version

**Comment by skohan** [comment]
Cool! Make a folder `C/Linux` and add your code with `README.md` which contains screenshots of the game and how to run it.

**Comment by codewdhruv** [comment]
its cpp @sohan-k

**Comment by skohan** [comment]
We already have CPP, for both Linux and Windows

**Comment by madjesc** [comment]
Can I make this?

**Comment by skohan** [comment]
Which language @Mkefs ?

**Comment by madjesc** [comment]
@sohan-k in C.
I have the linux version on C, it use SDL2
