### ISSUE TITLE
Cpp code

### ISSUE THREAD

**Issue by Mysterious-Owl** [sohan-k/Snake-game#9]
You can add this https://github.com/Mysterious-Owl/Snake-game-using-C
In cpp snake, I made it with some specific windows libraries, so its OS dependent, but its a single file, so easy to understand

**Comment by skohan** [comment]
Create a folder named C-windows and add your code in it and also the README file about compiling and executing. Leave a PR then.

**Comment by skohan** [comment]
Opened at #11 
Please star the repo :)
